title: UncertainAlex's cute website
email: dyingsoul6724@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my cute lil website! this is my about me, go check it out!! :3
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://uncertainalex.estrogen.monster/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  UncertainAlex